### PR TITLE
Dynare part updated

### PR DESCRIPTION
**Pull request by yoshikiwiskamp**
Hallo Christoph,

ich habe die Slides zum Dynare Teil und die mod-file überarbeitet.

VG
Yoshiki

### CODE REVIEW

**Review by schultkr — CHANGES_REQUESTED** [review]
You need to review the following issues:
I) Introduction_Dynare.mod
1 )  the endval block is not named endval in the code. See line 123

II) Slieds
1) on page 35 the FOC for representative households reads sigm_t^-sigma and not c_t^-sigma
2) the slides stsrting from chapter 4  are all duplicated. Remove one slide.
3) Further chapter 5 is not included and the appendix shows up after chapter 4

**Comment by yoshikiwiskamp** [comment]
Dear Christoph,

I am afraid I do not understand any of your remarks.

Regarding "Introduction_Dynare.mod": 
The part starting in line 123 follows the "endval-block" example presented in the slides (p. 73). As long as there is no issue with this example in general, the code should be correct.

Regarding the slides:
(1) I think it has to be c_t^-sigma on p.35. 
(2)+(3) I do not obtain this issue when compiling the pdf on my computer. I also do not see such patterns in the code that I have forked. Chapter 5, for example, starts in line 2505, as it should be the case.

To ensure that we are talking about the same thing, I have uploaded the relevant material in my folder "Dynare" --> "current version". I would be grateful if you could check whether this version works fine. 

Best,
Yoshiki

**Comment by schultkr** [comment]
> 
> 
> Dear Christoph,
> 
> I am afraid I do not understand any of your remarks.
> 
> Regarding "Introduction_Dynare.mod":
> The part starting in line 123 follows the "endval-block" example presented in the slides (p. 73). As long as there is no issue with this example in general, the code should be correct.
> 
> Regarding the slides:
> (1) I think it has to be c_t^-sigma on p.35.
> (2)+(3) I do not obtain this issue when compiling the pdf on my computer. I also do not see such patterns in the code that I have forked. Chapter 5, for example, starts in line 2505, as it should be the case.
> 
> To ensure that we are talking about the same thing, I have uploaded the relevant material in my folder "Dynare" --> "current version". I would be grateful if you could check whether this version works fine.
> 
> Best,
> Yoshiki

**Comment by schultkr** [comment]
Hello @yoshikiwiskamp ,
Sorry! My mistake I used the browser to check your work. It displayed your changes not completely and I just saw this:
1)
grafik

2) I was looking in the current master folder where sigma_t^-sigma  was still there instead of c_t^-sigma.
grafik
3) The duplicates are only visible in the pdf using the browser to display them. I will merge the pull request.
grafik


Best wishes
Christoph

**Pull request merged**
